apiVersion: v1
kind: Service
metadata:
  name: shopping-backend
spec:
  selector:
    app: shopping
    tier: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
