apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-backend
  labels:
    app: shopping
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shopping
      tier: backend
  template:
    metadata:
      labels:
        app: shopping
        tier: backend
    spec:
      containers:
      - name: shopping-backend
        image: dein-docker-user/shopping-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://shopping-db:3306/shopping"
