apiVersion: v1
kind: Service
metadata:
  name: shopping-db
spec:
  selector:
    app: shopping
    tier: database
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
