apiVersion: v1
kind: Service
metadata:
  name: shopping-frontend
spec:
  selector:
    app: shopping
    tier: frontend
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: LoadBalancer
