version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    container_name: shoppinglist-app

#services:
#  frontend:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    ports:
#      "3000:3000"
#  environment:
#    REACT_APP_BASE_URL=http://localhost:8080/api/items Adjust to the backend service in Docker
#  deploy:
#    replicas: 3  # Scale the number of frontend instances to 3
#  networks:
#    app-network

#  backend:
#    build:
#      context: ./backend
#      dockerfile: Dockerfile
#    ports: